/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compact capture with only name and text -- used by graph-mode imports
 * where position and node-type data are not consumed by the caller.
 */
export interface CompactCapture {
  name: string
  text: string
}

export interface CompactMatch {
  patternIndex: number
  captures: Array<CompactCapture>
}

export interface CompactQueryResults {
  imports: Array<CompactMatch>
}

export interface NativeCapture {
  name: string
  text: string
  nodeType: string
  start: NativePoint
  end: NativePoint
}

export interface NativeMatch {
  patternIndex: number
  captures: Array<NativeCapture>
}

export interface NativePoint {
  row: number
  column: number
  index: number
}

export interface NativeQueryResults {
  imports: Array<NativeMatch>
  exports: Array<NativeMatch>
  locals: Array<NativeMatch>
  importBindings: Array<NativeMatch>
}

/**
 * Run only the imports query and return compact results (name + text only).
 * This is the graph-mode entrypoint optimized for minimal marshaling.
 */
export declare function runImportsQueryCompact(source: string, languageId: string, importsQuery: string): CompactQueryResults

export declare function runLanguageQueries(source: string, languageId: string, importsQuery: string, exportsQuery: string, localsQuery: string, importBindingsQuery: string): NativeQueryResults

export declare function supportedLanguageIds(): Array<string>
