/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NativeCapture {
  name: string
  text: string
  nodeType: string
  start: NativePoint
  end: NativePoint
}

export interface NativeMatch {
  patternIndex: number
  captures: Array<NativeCapture>
}

export interface NativePoint {
  row: number
  column: number
  index: number
}

export interface NativeQueryResults {
  imports: Array<NativeMatch>
  exports: Array<NativeMatch>
  locals: Array<NativeMatch>
  importBindings: Array<NativeMatch>
}

export declare function runLanguageQueries(source: string, languageId: string, importsQuery: string, exportsQuery: string, localsQuery: string, importBindingsQuery: string): NativeQueryResults

export declare function supportedLanguageIds(): Array<string>
