export * from "./languages.js";
export {
  sliceText,
  unquote,
  toRange,
  listProjectFiles,
  discoverProjectFiles,
  stripJsLikeComments,
  stripPythonCommentsAndStrings,
  loadNearestTsconfigFor,
  loadWorkspaceConfig,
  resolveSpecifier,
  resolvePythonModule,
  resolveWorkspacePackage,
  resolvePackageSubpath,
  getGitHead,
  listChangedFiles,
  clearImportResolutionCaches,
  clearResolutionCaches,
} from "./util.js";
export type {
  ProjectFileDiscoveryOptions,
  ProjectFileInfo,
  ProjectFileKind,
  ProjectFileRole,
  ProjectFileType,
} from "./util.js";
export {
  collectGraph,
  graphToDOT,
  graphToMermaid,
  astGrep,
  textGrep,
  buildSymbolGraph,
  buildSymbolGraphDetailed,
  graphToMermaidSymbols,
  graphToDOTSymbols,
  graphToMermaidSymbolsWithFiles,
  graphToDOTSymbolsWithFiles,
  getDependencies,
  getReverseDependencies,
  getShortestPath,
  findCycles,
  findDetailedCycles,
  sortDetailedCycles,
  getUnresolvedImports,
  getHotspots,
  type DependencyNode,
  type GraphBuildOptions,
  type SymbolGraph,
  type SymbolNodeKind,
  type DetailedCycle,
  type CycleInternalEdge,
  type CycleSortMode,
} from "./graphs.js";
export {
  parseSymbolQuery,
  querySymbols,
  querySymbolNeighbors,
  type SymbolQuery,
  type NeighborQuery,
  type NeighborResult,
} from "./query.js";
export { graphToTriples, type Triple, type TripleNode } from "./triples.js";
export type { Pos, Range, FileId, EdgeTo, Edge, Graph } from "./types.js";
export {
  SymbolKind,
  type SymbolDef,
  type SymbolHandle,
  type ExportEntry,
  type ImportBinding,
  type ModuleIndex,
  type ProjectIndex,
  type ResolvedExport,
  type ResolutionProvenance,
  type BuildReport,
  type BuildOptions,
  type CacheReport,
  type BuildTimingReport,
  type BuildFileReport,
  type FallbackImportExtractionReport,
  type GraphReport,
  type ManifestReport,
  type NativeBackendFallbackReason,
  type NativeBackendReport,
  type BackendReport,
  type WorkerPoolReport,
  type GraphDeltaReport,
  type FindReferencesResult,
  type Reference,
  parseFile,
  collectLocalsAndExportsFromSource,
  collectImportsForFile,
  buildProjectIndex,
  buildProjectIndexFromFiles,
  buildProjectIndexIncremental,
  buildGraphDelta,
  resolveExport,
  goToDefinition,
  findReferences,
  buildScopeIndexFromSource,
  resolveImported,
  symbolId,
  defFromSymbolId,
  resolveSymbolId,
  goToDefinitionById,
  findReferencesById,
  type SymbolListItem,
  listSymbols,
  getApiSurface,
  type ApiSurface,
} from "./indexer.js";
export {
  analyzeImpactFromDiff,
  analyzeImpactStreaming,
  collectImpactContext,
  listCandidateTestFiles,
  type Diff,
  type FileChange,
  type Hunk,
  type ChangedSymbol,
  type ImpactItem,
  type ImpactReason,
  type ImpactReport,
  type CompactImpactReport,
  type ImpactStreamSummaryReport,
  IMPACT_SCHEMA_VERSION,
  type ImpactOptions,
  type ImpactStreamingOptions,
  type DiffProviderOptions,
  type ImpactContext,
  type CandidateTestFile,
  type ImpactStreamChunk,
} from "./impact/index.js";
export {
  CodeReviewSession,
  SessionManager,
  createCodeReviewSession,
  type ICodeReviewSession,
  type SessionOptions,
  type SessionStatus,
} from "./session.js";
export {
  getBuildPreset,
  getImpactPreset,
  getSessionPreset,
  mergePreset,
  BUILD_PRESETS,
  IMPACT_PRESETS,
  SESSION_PRESETS,
  type PresetName,
} from "./presets.js";
export {
  type PartialResult,
  type PartialError,
  success,
  partial,
  failed,
  withPartialResults,
  combinePartialResults,
  mapPartialResult,
  filterErrorsBySeverity,
  summarizePartialResult,
} from "./util/partialResults.js";
export {
  LazyArray,
  LazyProjectIndex,
  createSymbolLoader,
  type LazyModuleIndex,
  type LazyLoadOptions,
} from "./util/lazySymbols.js";
export {
  computeSymbolHash,
  symbolIdentifier,
  detectSymbolChanges,
  computeFileSymbolHashes,
  type SymbolHash,
  type SymbolManifestEntry,
} from "./util/symbolHash.js";
export {
  tool_impactJSON,
  tool_impactFromDiffText,
  tool_getFileOverview,
  tool_findSymbol,
  tool_listProjectFiles,
  tool_getGraph,
  tool_getDependencies,
  tool_getReverseDependencies,
  tool_getHotspots,
  tool_goToDefinition,
  tool_findReferences,
  type ToolFileOverview,
  type ToolFileOverviewImport,
  type ToolFileOverviewDefinition,
  type ToolFileOverviewResult,
  type ToolSymbolMatch,
  type ToolDependencyEntry,
  type ToolHotspotEntry,
} from "./agent-tools.js";
export {
  writeGraphSqlite,
  updateGraphSqlite,
  queryGraphSqlite,
  queryGraphSqliteRaw,
  type SqliteGraphOptions,
  type SqliteGraphUpdateOptions,
  type GraphQueryResult,
  type RawSqlResult,
} from "./sqlite.js";
export { chunkFile, type Chunk, type ChunkFileOptions } from "./chunking/chunkFile.js";
export { chunkTextFile, type TextChunkOptions } from "./chunking/chunkTextFile.js";
export { chunkSFCFile, type ChunkSFCOptions } from "./chunking/chunkSFC.js";
export { LANG_CONFIGS, type LanguageConfig } from "./bootstrap/treeSitterLanguages.js";
export {
  buildReviewReport,
  type ReviewDepth,
  type ReviewDiagnostics,
  type ReviewReport,
  type ReviewRiskLevel,
  type ReviewRiskSummary,
  type ReviewTask,
  type ReviewTaskPriority,
  type ReviewBuildReport,
  type ReviewTimingReport,
} from "./review.js";
export {
  type NativeRuntimeMode,
  type NativeQueryScope,
  isNativeTreeSitterAvailable,
  getNativeTreeSitterLoadError,
  getNativeTreeSitterSupportedLanguageIds,
} from "./native/treeSitterNative.js";
